print("Le Bich Phuong Ha")
print("Bao gio con duong cung mat tuoi nhu lan gap go dau")
print("Tinh thuong khong bao gio noi rang day la lan cuoi")
print("\"\\\\\\\Ba")
print("\"\\\\\\\\Ba")
print('Ba')
print("\"Bao gio con duong cung mat tuoi nhu lan gap go dau")
print("Tinh thuong khong bao gio noi rang day la lan cuoi\"")
print("\"Bao giờ con đường cũng mát tươi như lần gặp gỡ đầu")
print("Tình thương không bao giờ nói rằng đây là lần cuối \"")
#print("Ha")
# print("Ha")
print('Hello, world!')
print("Le Bich Phuong Ha")
print("Bao gio con duong cung mat tuoi nhu lan gap go dau")
print("Tinh thuong khong bao gio noi rang day la lan cuoi")
print('"sing"')
print('Ba')
print("An","Dinh","Chanh niem")
print("Line 1\nLine 2")
print("Bao giờ con đường cũng mát tươi như lần gặp gỡ đầu\n Tình thương không bao giờ nói rằng đây là lần cuối")
#print("Ha")
print("\"\\\\\\\Bao gio con duong cung mat tuoi nhu lan gap go dau")
print("Tinh thuong khong bao gio noi rang day la lan cuoi\"")
print("Bao giờ con đường cũng mát tươi như lần gặp gỡ đầu")
print("Tình thương không bao giờ nói rằng đây là lần cuối")
# print("Ko in ra")